version: '3.7'

volumes:
  caddy_data: {}


networks:
  caddy:
    name: caddy

services:
  poketype:
    container_name: docker-poketypes
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8088
    networks:
      - caddy
    environment:
      - GIN_MODE=release
    labels:
      caddy: http://poke.wouaib.ch
      caddy.reverse_proxy: "{{upstreams 8088}}"
      # caddy.log.level: DEBUG

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    restart: unless-stopped
